#! /bin/bash

sxhkd &

bspc monitor -d 1 2 3 4 5 6 7 8 9 10

bspc config top_padding          0
bspc config bottom_padding       0
bspc config border_width         2
bspc config window_gap           8

bspc config split_ratio          0.5
bspc config borderless_monocle   true
bspc config gapless_monocle      true
bspc config click_to_focus       any
bspc config honor_size_hints     true
bspc config ignore_ewmh_focus    true

bspc rule -a firefox desktop='1' split_ratio=0.7 follow=off
bspc rule -a jetbrains-idea-ce desktop='2' follow=off
bspc rule -a Viewnior state=floating
# bspc rule -a Chromium desktop='^2'
# bspc rule -a mplayer2 state=floating
# bspc rule -a Kupfer.py focus=on
# bspc rule -a Screenkey manage=off

# fix Java apps
wmname LG3D

${HOME}/.config/polybar/launch.sh bspwm
